services:
    opengsync-app:
        image: opengsync-app:latest
        platform: linux/amd64
        user: "${PUID:-1000}:${PGID:-1000}"
        container_name: opengsync-app
        restart: always
        build:
            context: .
            dockerfile: ./services/Dockerfile
            target: opengsync-app
        command: >
            gunicorn -w 4 --bind 0.0.0.0:${OPENGSYNC_PORT} 'scripts.wsgi:create_app(config_path="/app/opengsync.yaml")'
        volumes:
            - compiled_css:/static/style/compiled:ro
            - ${UPLOADS_DIR}:/uploads
            - ${MEDIA_DIR}:/media
            - ${LOG_DIR}/opengsync:/logs
        environment:
            TZ: ${TIMEZONE}
            OPENGSYNC_PORT: ${OPENGSYNC_PORT}
            REDIS_PORT: ${REDIS_PORT}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
            MAIL_SERVER: ${MAIL_SERVER}
            MAIL_PORT: ${MAIL_PORT}
            MAIL_SENDER: ${MAIL_SENDER}
            MAIL_PASSWORD: ${MAIL_PASSWORD}
            SECRET_KEY: ${SECRET_KEY}
            MAIL_USER: ${MAIL_USER}
            OPENGSYNC_DEBUG: 0
        expose:
            - ${OPENGSYNC_PORT}
        depends_on:
            postgres:
                condition: service_healthy
                restart: true
            sass-compiler:
                condition: service_completed_successfully
            redis-cache:
                condition: service_healthy
                restart: true
        healthcheck:
            test: ["CMD", "curl", "-f", "http://opengsync-app:${OPENGSYNC_PORT}/status/"]
            interval: 60s
            timeout: 10s
            retries: 5

    opengsync-celery-worker:
        platform: linux/amd64
        user: "${PUID:-1000}:${PGID:-1000}"
        container_name: opengsync-celery-worker
        restart: always
        build:
            context: .
            dockerfile: ./services/Dockerfile
            target: celery-worker
        environment:
            TZ: ${TIMEZONE}
            REDIS_PORT: ${REDIS_PORT}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
        volumes:
            - ./opengsync.yaml:/app/opengsync.yaml:ro
            - ${ILLUMINA_RUN_FOLDER}:/illumina_run_folder
            - ${LOG_DIR}/celery-worker:/logs
            - ${UPLOADS_DIR}:/uploads
        depends_on:
            opengsync-celery-beat:
                condition: service_started
                restart: true
            postgres:
                condition: service_healthy
                restart: true
        command: >
            celery -A opengsync_worker.celery worker --loglevel=info

    opengsync-celery-beat:
        platform: linux/amd64
        user: "${PUID:-1000}:${PGID:-1000}"
        container_name: opengsync-celery-beat
        restart: always
        build:
            context: .
            dockerfile: ./services/Dockerfile
            target: celery-worker
        environment:
            TZ: ${TIMEZONE}
            REDIS_PORT: ${REDIS_PORT}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
        volumes:
            - ./opengsync.yaml:/app/opengsync.yaml:ro
            - ${LOG_DIR}/celery-beat:/logs
        depends_on:
            postgres:
                condition: service_healthy
                restart: true
            redis-cache:
                condition: service_healthy
                restart: true
        command: >
            celery -A opengsync_worker.celery beat --loglevel=info

    backup-service:
        platform: linux/amd64
        container_name: backup-service
        restart: always
        build:
            context: ./services/opengsync-backup
        environment:
            TZ: ${TIMEZONE}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_REPLICATOR_PASSWORD}
            POSTGRES_USER: replicator
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_HOST: ${POSTGRES_HOST}
        volumes:
            - ${DB_DIR}/backup/dump:/backups/dump
            - ${DB_DIR}/backup/base:/backups/base
            - ${LOG_DIR}/backup:/var/log
        depends_on:
            postgres:
                condition: service_healthy

    sass-compiler:
        platform: linux/amd64
        container_name: sass-compiler
        build:
            context: .
            dockerfile: ./services/sass-compiler/Dockerfile
        restart: "no"
        environment:
            TZ: ${TIMEZONE}
        volumes:
            - compiled_css:/static/style/compiled
        command: "sass --style compressed --update /static/style/sass:/static/style/compiled"

    nginx:
        platform: linux/amd64
        container_name: nginx-proxy
        build:
            context: .
            dockerfile: ./services/nginx/Dockerfile
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - compiled_css:/static/style/compiled:ro
            - ${MEDIA_DIR}:/media:ro
            - ${UPLOADS_DIR}:/uploads:ro
        depends_on:
            opengsync-app:
                condition: service_started
                restart: true
            sass-compiler:
                condition: service_completed_successfully
        environment:
            TZ: ${TIMEZONE}
            OPENGSYNC_PORT: ${OPENGSYNC_PORT}
        command: /bin/bash -c "nginx -g 'daemon off;'"

    redis-cache:
        platform: linux/amd64
        container_name: redis-cache
        image: redis:8.0.3-alpine3.21
        restart: always
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        volumes:
            - ${CACHE_DIR}:/data
        environment:
            TZ: ${TIMEZONE}
        healthcheck:
            test: ["CMD", "redis-cli", "-p", "${REDIS_PORT}", "ping"]
            interval: 10s
            timeout: 10s
            retries: 5
        command: --port ${REDIS_PORT}

    postgres:
        user: "${PUID:-1000}:${PGID:-1000}"
        platform: linux/amd64
        container_name: postgres
        image: postgres:17-alpine
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGPORT: ${POSTGRES_PORT}
            TZ: ${TIMEZONE}
        expose:
            - ${POSTGRES_PORT}
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        volumes:
            - ./templates/postgres/postgresql.conf:/etc/postgresql.conf
            - ${DB_DIR}/postgres:/var/lib/postgresql/data:z
            - ${DB_DIR}/archive:/var/lib/postgresql/archive:z
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
            interval: 10s
            timeout: 10s
            retries: 5
        command: "postgres -c config_file=/etc/postgresql.conf"

    # pgadmin:
    #     platform: linux/amd64
    #     container_name: pgadmin
    #     image: dpage/pgadmin4:latest
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
    #         PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    #         TZ: ${TIMEZONE}
    #     ports:
    #         - ${PGADMIN_PORT}:80
    #     restart: always
    #     volumes:
    #         - ${DB_DIR}/pgadmin:/var/lib/pgadmin
    #     depends_on:
    #         postgres:
    #             condition: service_healthy
    #             restart: true
    #     attach: false  # no logs

volumes:
    compiled_css:
    yacht: