version: "3.8"

services:
    nginx:
        container_name: limbless-nginx-proxy
        build: ./services/nginx
        ports:
            - 80:80
        volumes:
            - static_volume:/usr/src/app/static:ro
        depends_on:
            limbless-app:
                condition: service_healthy
                restart: true
        environment:
            LIMBLESS_PORT: ${LIMBLESS_PORT}

    limbless-app:
        container_name: limbless-app
        build: ./services/limbless-app
        command: "gunicorn -w 4 --bind ${LIMBLESS_HOST}:${LIMBLESS_PORT} 'wsgi:app'"
        volumes:
            - ./services/limbless-app/limbless-server:/usr/src/app/limbless-server
            - ./uploads:/usr/src/app/uploads
            - ./media:/usr/src/app/media
            - ./logs/limbless:/usr/src/app/logs
            - ./data:/usr/src/app/data:ro
            - ./services/limbless-app/templates:/usr/src/app/templates:ro
            - static_volume:/usr/src/app/static:ro
        env_file: .env
        expose:
            - ${LIMBLESS_PORT}
        depends_on:
            postgres:
                condition: service_healthy
                restart: true

        healthcheck:
            test: ["CMD", "curl", "-f", "http://limbless-app:${LIMBLESS_PORT}/status"]
            interval: 10s
            timeout: 10s
            retries: 5

    postgres:
        container_name: limbless-postgres-db
        image: postgres:16rc1-alpine3.17
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        restart: always
        volumes:
            - ./db/postgres:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
            interval: 10s
            timeout: 10s
            retries: 5

    pgadmin:
        container_name: limbless-pgadmin
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        ports:
            - 5050:80
        restart: always
        volumes:
            - ./db/pgadmin:/var/lib/pgadmin
        depends_on:
            postgres:
                condition: service_healthy
                restart: true


volumes:
    static_volume: