services:
    opengsync-app:
        platform: linux/amd64
        user: "${USER}:${GROUP}"
        container_name: opengsync-app
        build:
            context: ./services/opengsync-app
            args:
                - APPUSER=${USER}
                - APPGROUP=${GROUP}
        restart: always
        command: >
            gunicorn -w 4 --bind 0.0.0.0:${OPENGSYNC_PORT} 'wsgi:create_app(config_path="/app/opengsync.yaml")'
        volumes:
            - ./services/opengsync-app/opengsync-server:/app/opengsync-server
            - ./services/opengsync-app/templates:/templates:ro
            - ./opengsync.yaml:/app/opengsync.yaml:ro
            - ./services/opengsync-app/static/:/static/:ro
            - compiled_css:/static/style/compiled:ro
            - ./app_data:/app_data
            - ${UPLOADS_DIR}:/uploads
            - ${DATA_DIR}/media:/media
            - ${DATA_DIR}/logs/opengsync:/logs
        env_file: .env
        environment:
            TZ: ${TIMEZONE}
        expose:
            - ${OPENGSYNC_PORT}
        depends_on:
            postgres:
                condition: service_healthy
                restart: true
            sass-compiler:
                condition: service_completed_successfully
                restart: false
            redis-cache:
                condition: service_healthy
                restart: true
        healthcheck:
            test: ["CMD", "curl", "-f", "http://opengsync-app:${OPENGSYNC_PORT}/status"]
            interval: 60s
            timeout: 10s
            retries: 5

    sass-compiler:
        container_name: sass-compiler
        build: ./services/sass-compiler
        environment:
            TZ: ${TIMEZONE}
        volumes:
            - ./services/opengsync-app/static/style/sass:/static/style/sass:ro
            - compiled_css:/static/style/compiled
        command: "sass --style compressed --update /static/style/sass:/static/style/compiled"

    celery-worker:
        user: "${USER}:${GROUP}"
        platform: linux/amd64
        container_name: celery-worker-prod
        build:
            context: ./services
            dockerfile: celery/Dockerfile
        env_file: .env
        environment:
            TZ: ${TIMEZONE}
        volumes:
            - ./opengsync.yaml:/app/opengsync.yaml:ro
            - ${ILLUMINA_RUN_FOLDER}:/illumina_run_folder
            - ${DATA_DIR}/logs/celery-worker:/logs
            - ${UPLOADS_DIR}:/uploads
        depends_on:
            celery-scheduler:
                condition: service_started
                restart: true
            postgres:
                condition: service_healthy
                restart: true
        restart: always
        command: >
            celery -A scheduler.celery worker --loglevel=info

    celery-scheduler:
        platform: linux/amd64
        container_name: celery-scheduler-prod
        build:
            context: ./services
            dockerfile: celery/Dockerfile
        env_file: .env
        environment:
            TZ: ${TIMEZONE}
        volumes:
            - ./opengsync.yaml:/app/opengsync.yaml:ro
        depends_on:
            postgres:
                condition: service_healthy
                restart: true
            redis-cache:
                condition: service_healthy
                restart: true
        restart: always
        command: >
            celery -A scheduler.celery beat --loglevel=info

    nginx:
        container_name: nginx-proxy
        build: ./services/nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./services/opengsync-app/static:/static:ro     # you might need to remove :ro when running for the first time
            - compiled_css:/static/style/compiled:ro
            - ${DATA_DIR}/media:/media:ro
            - ${UPLOADS_DIR}:/uploads:ro
        depends_on:
            opengsync-app:
                condition: service_started
                restart: true
            sass-compiler:
                condition: service_completed_successfully
                restart: false
        environment:
            TZ: ${TIMEZONE}
            OPENGSYNC_PORT: ${OPENGSYNC_PORT}
            OPENGSYNC_SERVER_NAME: ${OPENGSYNC_SERVER_NAME}
        command: /bin/bash -c "nginx -g 'daemon off;'"

    redis-cache:
        user: "${USER}:${GROUP}"
        container_name: redis-cache
        image: redis:8.0.3-alpine3.21
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        restart: always
        volumes:
            - ./cache:/data
        environment:
            TZ: ${TIMEZONE}
        healthcheck:
            test: ["CMD", "redis-cli", "-p", "${REDIS_PORT}", "ping"]
            interval: 10s
            timeout: 10s
            retries: 5
        command: --port ${REDIS_PORT}

    postgres:
        container_name: postgres
        user: "${USER}:${GROUP}"
        image: postgres:17.6-alpine3.22
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGPORT: ${POSTGRES_PORT}
            TZ: ${TIMEZONE}
        expose:
            - ${POSTGRES_PORT}
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        restart: always
        volumes:
            - ./templates/postgres/postgresql.conf:/etc/postgresql.conf
            - ${DB_DIR}/postgres:/var/lib/postgresql/data:z
            - ${DATA_DIR}/db_backup/wal:/var/lib/postgresql/backup
            - ${DATA_DIR}/db_backup/base:/var/lib/postgresql/base
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
            interval: 10s
            timeout: 10s
            retries: 5
        command: "postgres -c config_file=/etc/postgresql.conf"

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
            TZ: ${TIMEZONE}
        ports:
            - ${PGADMIN_PORT}:80
        restart: always
        volumes:
            - ${DB_DIR}/pgadmin:/var/lib/pgadmin
        depends_on:
            postgres:
                condition: service_healthy
                restart: true
        attach: false  # no logs

    yacht:
        container_name: yacht
        image: selfhostedpro/yacht:latest
        environment:
            TZ: ${TIMEZONE}
        ports:
            - ${YACHT_PORT}:8000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - yacht:/config
        restart: always

    celery-flower:
        platform: linux/amd64
        container_name: celery-flower-prod
        build:
            context: ./services
            dockerfile: celery/Dockerfile.flower
        environment:
            TZ: ${TIMEZONE}
        depends_on:
            redis-cache:
                condition: service_healthy
                restart: true
        ports:
            - 5555:5555
        restart: always
        command: >
            celery --broker=redis://redis-cache:${REDIS_PORT}/4 flower --port=5555 --basic-auth="${FLOWER_USER}:${FLOWER_PASSWORD}"

volumes:
    compiled_css:
    yacht: